import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Privacy Policy" };

const sections = [
  {
    title: "1. Information We Collect",
    body: "We collect information you provide directly (name, email, payment details), information generated by your use of the platform (bookings, searches, reviews), and technical data (IP address, browser type, device identifiers).",
  },
  {
    title: "2. How We Use Your Information",
    body: "We use your data to process bookings and payments, remember your account preferences, send booking confirmations and service updates, improve the platform, and comply with legal obligations.",
  },
  {
    title: "3. Information Sharing",
    body: "We share your information with partners only as necessary to fulfill your booking, with payment processors (Stripe, Flutterwave) to complete transactions, and with service providers who assist our operations. We do not sell your personal data.",
  },
  {
    title: "4. Cookies & Tracking",
    body: "We use cookies for authentication, remembering your preferences, and analytics. You can control cookie settings through your browser. Disabling certain cookies may affect platform functionality.",
  },
  {
    title: "5. Data Retention",
    body: "We retain your account data as long as your account is active. Booking records are retained for 7 years for financial compliance. You may request deletion of your account and associated data at any time.",
  },
  {
    title: "6. Your Rights",
    body: "Under Rwandan data protection law and GDPR (for EU residents), you have the right to access, correct, delete, or port your personal data. You also have the right to object to processing for marketing purposes.",
  },
  {
    title: "7. Security",
    body: "We implement industry-standard security measures including encryption in transit (TLS), encryption at rest, and access controls. However, no system is completely secure and we cannot guarantee absolute security.",
  },
  {
    title: "8. Children's Privacy",
    body: "Tembea is not intended for children under 16. We do not knowingly collect data from minors. If you believe a child has provided us personal data, please contact us immediately.",
  },
  {
    title: "9. Changes to This Policy",
    body: "We may update this policy and will notify you of significant changes via email or prominent notice on the platform.",
  },
  {
    title: "10. Contact Us",
    body: "For privacy inquiries or to exercise your rights, contact our Data Protection Officer at privacy@tembea.rw or write to Tembea Ltd, KG 7 Ave, Kigali, Rwanda.",
  },
];

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-gray-50 py-16">
      <div className="tembea-container max-w-3xl">
        <div className="mb-10">
          <span className="section-kicker">Legal</span>
          <h1 className="text-4xl font-black text-gray-900 mt-2">Privacy Policy</h1>
          <p className="text-sm text-gray-500 mt-2">
            Last updated: June 2025 &nbsp;·&nbsp;{" "}
            <Link href="/terms" className="text-[#145A32] font-semibold hover:underline">
              Terms of Service
            </Link>
          </p>
        </div>

        <div className="bg-white rounded-2xl shadow-soft p-8 space-y-8">
          <p className="text-gray-600 leading-relaxed">
            Tembea Ltd is committed to protecting your privacy. This policy explains how we collect, use, and protect
            your personal information when you use the Tembea platform.
          </p>

          {sections.map((s) => (
            <div key={s.title} className="space-y-2">
              <h2 className="text-lg font-black text-gray-900">{s.title}</h2>
              <p className="text-gray-600 leading-relaxed">{s.body}</p>
            </div>
          ))}
        </div>
      </div>
    </main>
  );
}
